# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authors', models.TextField(help_text='Separate each item by comma.', max_length=500)),
                ('tags', models.TextField(blank=True, help_text='Separate each item by comma.', null=True)),
                ('publisher', models.TextField(max_length=200)),
                ('isbn', models.TextField(max_length=200)),
                ('shelf', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
    ]
